[build]
  command = "npm run build"
  publish = ".next/static"
  functions = ".next/serverless"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false