import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

// import UserProvider from "@/components/context/user-provider";
import { GoogleOAuthProvider } from '@react-oauth/google';
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import PaymentClientProvider from "@/components/context/payment/PaymentProvider";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_CLIENT_ID!}>
      <ClerkProvider>
        <PaymentClientProvider>
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <Header/>
              {children}
              <Footer/>
            </body>
          </html>
        </PaymentClientProvider>
      </ClerkProvider>
    </GoogleOAuthProvider>
  );
}
