import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import Footer from "@/components/Footer";
import Header from "@/components/header/header";
import OfflineSyncManager from "@/components/OfflineSyncManager";
import GlobalUsageLimitHandler from "@/components/modals/GlobalUsageLimitHandler";
import SentryClientInit from "@/components/SentryClientInit";


const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://cellilox.com";

export const metadata: Metadata = {
    metadataBase: new URL(siteUrl),
    title: "Cellilox | Home",
    description:
        "Spin up an AI agent for any document — invoices, contracts, bank statements and more. It reads every file you drop in and turns it into a clean, structured spreadsheet.",
    keywords: [
        "document processing",
        "AI document agent",
        "data entry automation",
        "invoice extraction",
        "contract analysis",
        "document AI",
        "Cellilox",
    ],
    alternates: {
        canonical: "/",
    },
    icons: {
        icon: "/favicon.ico",
    },
    manifest: "/manifest.json",
    openGraph: {
        type: "website",
        url: siteUrl,
        siteName: "Cellilox",
        title: "Cellilox | AI agent for every document",
        description:
            "Pick a document type and spin up an AI agent that reads every file you drop in and turns it into a clean, structured spreadsheet you can query in plain language.",
        // og:image is generated by src/app/opengraph-image.tsx
    },
    twitter: {
        card: "summary_large_image",
        title: "Cellilox | AI agent for every document",
        description:
            "Pick a document type and spin up an AI agent that reads every file you drop in and turns it into a clean, structured spreadsheet you can query in plain language.",
        // twitter:image is generated by src/app/twitter-image.tsx
    },
    robots: {
        index: true,
        follow: true,
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    suppressHydrationWarning
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <SentryClientInit />
                    <Header />
                    <OfflineSyncManager />
                    <GlobalUsageLimitHandler />
                    {children}

                    <Footer />

                </body>
            </html>
        </ClerkProvider>
    );
}
